"""Client display catalog, shared by code and integration documentation.

HTTP meanings: RFC 9110 and RFC 6585. Suggestions are client guidance;
no entry authorizes retries or asserts billing/refund outcomes.
"""

HTTP_ERROR_HINTS = {
    400: "请求参数或素材不符合接口要求。请检查原始错误指出的字段、必填项、JSON结构和模型参数。",
    401: "身份验证失败。请核对API密钥、有效期，以及密钥与API地址是否属于同一服务商。",
    402: "接口要求检查支付或可用额度。请结合原始错误核查账号余额、密钥额度和模型配额；不能仅凭状态码判断实际扣费。",
    403: "访问被拒绝。请核对账号、模型、素材权限和服务商限制；不要直接认定密钥错误或余额不足。",
    404: "接口、模型或请求的资源不存在。请检查API基础地址、接口路径、实际模型ID及任务或素材ID是否属于当前渠道。",
    405: "接口不接受当前HTTP请求方法。请按接入文档核对GET、POST等方法和接口路径，不自动换方法重发。",
    406: "接口无法提供客户端要求的响应格式。请检查Accept请求头和接口支持的返回格式。",
    407: "代理服务器要求身份验证。请检查代理账号和代理配置；这不等同于妙笔API密钥无效。",
    408: "服务端等待接收请求超时。请检查网络和上传过程；提交结果未知时先核查原任务，不重复提交付费请求。",
    409: "请求与当前资源状态冲突。请核查已有任务、资源版本及幂等标识；不能直接换新标识重复生成。",
    410: "请求的资源已不再可用。请核查素材或结果有效期，优先通过原任务取得新的有效引用。",
    411: "接口要求提供请求内容长度。请检查上传方式与Content-Length，由HTTP客户端正确计算。",
    412: "请求的前置条件不满足。请检查资源版本及If-Match等条件头，核对最新状态后再处理。",
    413: "素材大小或请求体超过接口限制。请减少文件体积或批次数量，并核对该模型允许的上传大小。",
    414: "请求URL过长。请检查是否将长文本或素材放入URL参数，按接口要求使用请求体传递。",
    415: "媒体格式或内容类型不受支持。请检查Content-Type、文件实际格式和编码，不能只修改文件后缀。",
    416: "请求下载的字节范围无效。请核查文件长度和Range参数，修正断点续传；无需重新生成。",
    417: "服务端不能满足Expect请求头要求。请核对HTTP客户端和代理的请求头配置。",
    421: "请求被发送到无法处理该目标的服务。请检查API域名、Host、代理路由与连接配置。",
    422: "请求结构可读取，但参数或素材无法按要求处理。请检查具体字段值、参数组合和素材限制。",
    425: "服务端拒绝可能被重放的过早请求。请检查客户端或代理的早期数据设置，并核查原请求状态。",
    426: "服务端要求升级通信协议。请检查接口要求、客户端版本和代理支持的协议。",
    428: "请求缺少服务端要求的前置条件。请按接口文档补齐版本或条件头，避免覆盖已变化的资源。",
    429: "请求受到限流或配额限制，具体维度需看原始错误。请检查频率、并发、配额和队列；已有任务先查询，不自动重提。",
    431: "请求头过大。请检查重复请求头、过长Cookie和凭据字段，减少无关头部。",
    500: "服务端内部异常。请保留任务ID和原始错误交服务商排查；提交结果未知时先核查原任务。",
    501: "服务端未实现处理本请求所需的功能。请核对接口路径、HTTP方法和当前渠道支持的能力，由服务商确认；反复重试通常不能解决功能缺失。",
    502: "网关从上游收到无效响应。请保留任务ID让服务商核查上游连接与响应；不能直接归因为本机网络问题。",
    503: "服务暂时不可用，可能繁忙或维护。请查看服务状态和响应中的等待提示，先确认已有任务再安排后续请求。",
    504: "网关等待上游响应超时。生成可能仍在进行，请继续查询原任务或让服务商确认，不自动重复生成。",
    505: "服务端不支持当前HTTP协议版本。请检查HTTP客户端、代理及接口要求的协议版本。",
    511: "当前网络要求先完成接入认证。请检查网络登录页面或网关认证；这不等同于妙笔API密钥错误。",
    423: "资源处于锁定状态。请检查是否有其他操作占用，按接口规则等待或处理锁状态。",
    424: "本操作依赖的前序操作失败。请先检查前序任务或素材处理结果，不只重试当前步骤。",
    451: "资源因法律要求而不可用。请查看原始说明并联系服务商确认适用限制。",
    507: "服务端存储空间不足。请联系服务商核查存储容量；这不等同于用户本地磁盘已满。",
    520: "收到非标准网关错误520；在Cloudflare语义下表示源站返回未知异常。请让服务商核查实际网关及源站日志。",
    521: "收到非标准网关错误521；在Cloudflare语义下表示源站拒绝连接。请让服务商核查源站服务和防火墙。",
    522: "收到非标准网关错误522；在Cloudflare语义下表示连接源站超时。请让服务商核查源站连接。",
    523: "收到非标准网关错误523；在Cloudflare语义下表示源站不可达。请让服务商核查源站地址和路由。",
    524: "收到非标准网关错误524；在Cloudflare语义下表示连接建立后等待响应等过程超时。请保留原任务，核查状态。",
    525: "收到非标准网关错误525；在Cloudflare语义下表示网关与源站TLS握手失败。请让服务商核查源站TLS配置。",
    526: "收到非标准网关错误526；在Cloudflare语义下表示源站证书无效。请让服务商核查证书；不要关闭客户端证书校验。",
}

# Match only actual failure messages, never prompts or successful model text.
BUSINESS_ERROR_HINTS = [
    ("token_rate", ("tokens per minute", "token rate limit", "tpm limit", "tpm exceeded"), "Token处理速率超过限制。请降低并发、减少同时发送的长文本和历史记录；这与单条上下文长度超限不同。"),
    ("concurrency", ("concurrency limit", "concurrent requests", "too many active tasks", "max concurrency"), "同时运行的任务超过并发限制。请等待已有任务结束，并减少同时提交的任务数。"),
    ("request_rate", ("requests per minute", "rpm limit", "rpm exceeded"), "单位时间内请求次数超过限制。请分散发送时间，检查多个页面或实例是否共用同一密钥。"),
    ("period_quota", ("daily quota", "requests per day", "rpd limit", "daily limit"), "当前周期配额已用尽。请检查配额及明确返回的重置时间；短时间反复请求不能恢复额度。"),
    ("queue_full", ("queue full", "queue is full", "queue capacity exceeded"), "当前任务队列已满。请减少新任务提交，等待队列释放；已取得任务ID的请求继续查询原任务。"),
    ("capacity", ("overloaded", "capacity exhausted", "no available capacity"), "当前服务处理容量不足。请保留原任务信息，稍后使用或手动选择已经接入的其他可用模型。"),
    ("quota", ("insufficient_quota", "quota exceeded"), "可用额度或配额不足，当前信息不一定表示账户余额不足。请核查密钥额度、模型配额及具体限制维度。"),
    ("unsupported_input", ("does not support image", "does not support audio", "does not support video", "unsupported input type"), "当前模型或接口不支持这种输入类型。请核对图片、音频或视频能力，选择已接入的对应多模态模型。"),
    ("truncated_output", ("output truncated", "max_tokens exceeded", "finish_reason: length"), "模型输出因长度限制被截断。请减少单次任务范围或调整输出预算，保留已有内容，不将其标记为完整成功。"),
    ("empty_output", ("empty response", "empty completion", "no image returned", "no images returned"), "未取得当前功能需要的有效结果。请核对响应结构和模型输出类型，保留响应信息，不自动重新生成。"),
    ("invalid_image", ("invalid image data", "cannot identify image file", "incorrect padding", "invalid base64"), "图像或Base64数据无效或不完整。请核对媒体内容和编码，不把错误页面或占位图当作生成成功。"),
    ("mask_mismatch", ("mask size mismatch", "mask and image must", "mask dimensions"), "蒙版与编辑图片不匹配。请检查尺寸、通道和格式，缩放图片后保持蒙版对齐。"),
    ("stream_interrupted", ("chunkedencodingerror", "response ended prematurely", "incomplete read", "incompleteread", "stream interrupted"), "响应传输中断，内容可能不完整。请保留已接收内容和请求标识，核查状态；不要自动重发整条付费请求。"),
    ("disk_full", ("no space left on device", "disk full", "磁盘空间不足"), "本地磁盘空间不足，保存结果失败。请清理空间并恢复保存或下载；生成可能已成功，不要重新生成。"),
    ("local_permission", ("permissionerror", "winerror 5", "errno 13"), "本地文件访问被拒绝。请检查目标目录权限、文件占用和保存路径；保存失败不代表生成失败。"),
    ("codec", ("unknown encoder", "encoder not found", "ffmpeg not found", "ffprobe not found"), "本地媒体处理组件或编码器缺失。请检查ffmpeg、ffprobe及所需编码器的安装与路径。"),
    ("redirect", ("toomanyredirects", "too many redirects"), "请求发生过多重定向。请检查API或素材URL及代理配置，不把认证信息转发到未知目标。"),
]
